### ISSUE TITLE
WaitGroup reuse issue

### ISSUE THREAD

**Issue by 0xhaven** [nhooyr/TunneLS#3]
While running some performance testing, I came across this panic.

```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 629 [running]:
panic(0x1ab480, 0xc4203043d0)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
sync.(*WaitGroup).Wait(0xc42000a5d8)
    /usr/local/Cellar/go/1.7.1/libexec/src/sync/waitgroup.go:133 +0xfe
main.(*node).tunnel(0xc42000a500, 0x2ba820, 0xc42002c240, 0x2ba760, 0xc4203cb180)
    /Users/jhaven/gopath/src/github.com/nhooyr/TunneLS/node.go:328 +0x3b5
main.(*node).dialAndTunnel(0xc42000a500, 0x2ba820, 0xc42002c240)
    /Users/jhaven/gopath/src/github.com/nhooyr/TunneLS/node.go:319 +0x202
created by main.(*node).listenAndServeErr
    /Users/jhaven/gopath/src/github.com/nhooyr/TunneLS/node.go:295 +0x318
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 627 [running]:
panic(0x1ab480, 0xc420a72220)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
sync.(*WaitGroup).Wait(0xc42000a5d8)
    /usr/local/Cellar/go/1.7.1/libexec/src/sync/waitgroup.go:133 +0xfe
main.(*node).tunnel(0xc42000a500, 0x2ba820, 0xc42002c230, 0x2ba760, 0xc4203cbc00)
    /Users/jhaven/gopath/src/github.com/nhooyr/TunneLS/node.go:328 +0x3b5
main.(*node).dialAndTunnel(0xc42000a500, 0x2ba820, 0xc42002c230)
    /Users/jhaven/gopath/src/github.com/nhooyr/TunneLS/node.go:319 +0x202
created by main.(*node).listenAndServeErr
    /Users/jhaven/gopath/src/github.com/nhooyr/TunneLS/node.go:295 +0x318
```

It appears that by using a single `WaitGroup` for all `tunnel`/`copy` calls on a `node`, we're running into a race condition when multiple tunnels are being created simultaneously (e.g. in high traffic or testing environments).

**Comment by nhooyr** [comment]
This repository is actually deprecated. I use [tlsmuxd](https://github.com/nhooyr/tlsmuxd) and [tlswrapd](https://github.com/nhooyr/tlswrapd) now.

**Comment by nhooyr** [comment]
But yes, this is a bug. I have no idea what I was thinking. Can you create a PR with a fix?

**Comment by nhooyr** [comment]
If you can, you should switch to them as they are both **MUCH** better written than TunneLS.

**Comment by 0xhaven** [comment]
*PR submitted*. I saw those (when you posted them on reddit a few days ago, actually), but they're nowhere near as well documented, making me hesitant to use them.

What benefits would they provide over TunnelS as a TLS proxy?

**Comment by nhooyr** [comment]
1. Code is much more simple and easy to maintain. Likely more performant too. 
2. tlsmuxd has automated certificates via lets encrypt
3. tlsmuxd also lets you multiplex based on SNI and hostnames
4. tlswrapd supports ALPN

It does depend on your needs though because tlsmuxd only supports ACME and lets encrypt for certificates. You cannot use your own. tlsmuxd and tlswrapd both also do not support client authentication.

If you really need those features, they aren't very hard to implement in tlsmuxd/tlswrapd. I just haven't gotten around to it yet.

Also, I have a much stronger interest in maintaining them and as such, I would be more willing to respond to feature requests and what not. This repository is basically dead for me in terms of actual development.

**Comment by nhooyr** [comment]
And I don't mind breaking changes to either right now if you see a approach that is better than what I am doing.
